export default {
  ADD_VENUES: 'ADD_VENUES',
  ADD_RECOMMENDED: 'ADD_RECOMMENDED',
  ADD_MOSTLOVED: 'ADD_MOSTLOVED',
  ADD_MOSTVISITED: 'ADD_MOSTVISITED',
  ADD_USERLOVED: 'ADD_USERLOVED',
  ADD_USERVISITED: 'ADD_USERVISITED',
  ADD_RECOMMENDEDOFFERS: 'ADD_RECOMMENDEDOFFERS',
  ADD_WITHOFFERS: 'ADD_WITHOFFERS',
  INIT_FETCH: 'INIT_FETCH',
  CANCEL_FETCH: 'CANCEL_FETCH',
  SET_AREA: 'SET_AREA',
};
